name: Release
on:
  push:
    branches:
      - main
      - beta
      - alpha
env:
  CI: true
  HUSKY_SKIP_HOOKS: 1
  HUSKY: 0
  GITHUB_TOKEN: ${{ secrets.BOT_GIT_TOKEN }}
  GIT_AUTHOR_NAME: idex-bot
  GIT_AUTHOR_EMAIL: support@idex.io
  GIT_COMMITTER_NAME: idex-bot
  GIT_COMMITTER_EMAIL: support@idex.io
jobs:
  pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Check For PR
        env:
          REF: ${{ env.GITHUB_BASE_REF }}
          BASE: main
        run: |
          BRANCH=${GITHUB_REF##*/}
          [[ "$BRANCH" == "$BASE" ]] && exit 0;
          if [[ "$BRANCH" == "alpha" ]]; then
            BASE="beta"
          fi
          echo "Check If PR exists for $BRANCH --> $BASE"
          if [[ "$(gh pr list -R "$GITHUB_REPOSITORY" --base "$BASE" --state open --label "Release $BRANCH")" == "" ]]; then
            echo "Creating PR $BRANCH --> $BASE"
            RESULT=$(gh api repos/"${GITHUB_REPOSITORY}"/pulls -F head="$BRANCH" -F base="$BASE" -F title="Release $BRANCH" -F body="This PR was generated automatically.  Merging it will transition $BRANCH into ${BASE}.")
            PR_NUM=$(echo $RESULT | jq -r '.number')
            printf '{"labels": ["Release %s"]}' $BRANCH | gh api repos/"${GITHUB_REPOSITORY}"/issues/"${PR_NUM}"/labels --input -
          fi
  release:
    name: Release 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          check-latest: true
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline --non-interactive
      - name: Build Library
        run: yarn build
      # Build Documentation which will be commited by semantic-release
      - name: Build Documentation
        run: yarn generate:docs:commit
      - name: Semantic Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release